# Generated by Django 4.1.1 on 2022-09-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("admission_number", models.IntegerField(unique=True)),
                ("is_qualified", models.BooleanField(default=True)),
                ("average_score", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("student_capacity", models.IntegerField()),
                ("students", models.ManyToManyField(to="classroom.student")),
            ],
        ),
    ]
